NAME	:=	libftprintf.a

CC	:=	clang

DEBUG	:=	-g

INCLUDE	:=	include/

FLAGS	:=	-Wall -Wextra -Werror $(DEBUG) -I

ARCL	:=	ar -crs

SRCS	:=	srcs/ft_print_char.c		\
			srcs/ft_print_hex.c		\
			srcs/ft_print_nbr.c		\
			srcs/ft_print_ptr.c		\
			srcs/ft_print_str.c		\
			srcs/ft_print_u_nbr.c	\
			srcs/ft_printf.c

OBJS = $(SRCS:.c=.o)

# COLORS ================================================================= #

RED = \033[0;91m
GREEN = \033[0;92m
YELLOW = \033[0;93m
CYAN = \033[0;96m
WHITE = \033[0;97m

# ======================================================================== #

%.o : %.c
	@$(CC) $(FLAGS) $(INCLUDE) -c $< -o $@
	@echo "$(GREEN)Compiling:$(WHITE) $<"

all: $(NAME)

$(NAME): $(OBJS)
	$(ARCL) $(NAME) $(OBJS)
	@echo "$(YELLOW)- Program Name: $(WHITE)${NAME}"
	@echo "$(YELLOW)- Compiler: $(WHITE)${CC}"
	@echo "$(YELLOW)- Flags: $(WHITE)${FLAGS}"
	@echo "$(YELLOW)- Includes: $(WHITE)${INCLUDE}"

clean:
	@rm -f $(OBJS)
	@echo "$(RED)All $(CYAN)$(NAME)$(RED)'s objects removed with $(WHITE)${RM} $(YELLOW)"

fclean: clean
	@rm -f $(NAME)
	@echo "$(RED)...and $(CYAN)${NAME} $(RED)has been removed"

re: fclean all

.PHONY: all clean fclean re
.SILENT:
